
version: '3'

services:
  api:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - umuco-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - umuco-network

networks:
  umuco-network:
    driver: bridge

volumes:
  mongo-data:
